scalar Date

type Query {
    hello(name: String): String
    highscore: [Score]
    highscoreSnapshot: [HsSnapshot]
}

type Mutation {
    newScore(userid: String, score: Int, name: String): Score
    handshake(userid: String, name: String, _id: String): User
}

type HsSnapshot {
    caption: String
    rows: [Score]
}

type User {
    userid: String
    _id: String
    maxScore: String
    name: String
}

type Score {
    id: ID
    name: String
    userid: String
    time: String
    timestamp: Date
    score: Int
}
